### ISSUE TITLE
Milestone #1

### ISSUE THREAD

**Issue by perguth** [onlyjedis/replimate#1]
- [ ] Als Trinker moechte ich meinen `Verbrauch erfassen`, dh. welche Flasche ich wann getrunken habe.
- [ ] Als Kastenkaeufer moechte ich meine `Unkosten erfassen` und in die `Abrechnung` eingehen lassen.
- [ ] Als Trinker und Kastenkaeufer moechte ich eine `Abrechnung erhalten`, die meine angefallenen Kosten auflistet.
- [ ] Als Trinker und Kastenkaeufer moechte ich bei der `Abrechnung` Schulden und Uebertraege aller Nutzer auf 0 setzen koennen.
